package constants

const (
	ORDER_STATUS_PENDING   = "PENDING"
	ORDER_STATUS_CONFIRM   = "CONFIRM"
	ORDER_STATUS_SHIPPED   = "SHIPPED"
	ORDER_STATUS_COMPLETED = "COMPLETED"
	ORDER_STATUS_CANCELLED = "CANCELLED"
)

const (
	ORDERINPUT_STATUS_PENDING   = 1
	ORDERINPUT_STATUS_CONFIRM   = 2
	ORDERINPUT_STATUS_SHIPPED   = 3
	ORDERINPUT_STATUS_COMPLETED = 4
	ORDERINPUT_STATUS_CANCELLED = 5
)
