package constants

const (
	ORDER_STATUS_PENDING   = "PENDING"
	ORDER_STATUS_CONFIRM   = "CONFIRM"
	ORDER_STATUS_SHIPPED   = "SHIPPED"
	ORDER_STATUS_COMPLETED = "COMPLETED"
	ORDER_STATUS_CANCELLED = "CANCELLED"
)
