definitions:
  dto.CreateOrderRequest:
    properties:
      awb_number:
        type: string
      receiver:
        type: string
      sender:
        type: string
      total_weight:
        type: number
    type: object
  dto.UpdateOrderStatusRequest:
    properties:
      status:
        type: integer
    type: object
  httputils.BaseMeta:
    properties:
      limit:
        type: integer
      page:
        type: integer
      total_data:
        type: integer
      total_page:
        type: integer
    type: object
  httputils.BaseResponse:
    properties:
      data: {}
      error_message:
        type: string
      meta:
        $ref: '#/definitions/httputils.BaseMeta'
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /awb-stocks:
    get:
      consumes:
      - application/json
      description: '"List of AWB stocks"'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputils.BaseResponse'
      summary: List of AWB stocks
      tags:
      - AWB Stock
  /orders:
    get:
      consumes:
      - application/json
      description: '"Get an Order List"'
      parameters:
      - description: Page number
        example: 1
        in: query
        name: page
        type: integer
      - description: Search by AWB number substring
        example: '"001-10000001"'
        in: query
        name: awb
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputils.BaseResponse'
      summary: Get Order List
      tags:
      - Order
    post:
      consumes:
      - application/json
      description: '"Create an Order"'
      parameters:
      - description: Order request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputils.BaseResponse'
      summary: Create Order
      tags:
      - Order
  /orders/{id}:
    get:
      consumes:
      - application/json
      description: '"Get an Order by Order ID"'
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputils.BaseResponse'
      summary: Get Order by Order ID
      tags:
      - Order
  /orders/{id}/status:
    put:
      consumes:
      - application/json
      description: '"Update an Order Status"'
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      - description: 'Order status payload. Allowed values: 1=PENDING, 2=CONFIRM,
          3=SHIPPED, 4=COMPLETED, 5=CANCELLED'
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateOrderStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputils.BaseResponse'
      summary: Update Order Status
      tags:
      - Order
swagger: "2.0"
